apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat
  labels:
    app: cat
spec:
  replicas: 30
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: {{ .Values.catImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        livenessProbe:
          httpGet:
            path: /index.html
            port: 3000
        readinessProbe:
          httpGet:
            path: /index.html
            port: 3000
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "30m"
            memory: "128Mi"

