kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "cat-deny-from-other-namespaces"
  labels:
    app: cat
spec:
  podSelector: {}
  ingress:
    - from:
      - podSelector: {}
    - from:
      - namespaceSelector:
          matchLabels:
            system: ingress

