apiVersion: v1
kind: Service
metadata:
  name: cat-service
  annotations:
  labels:
    app: cat
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http  
  selector:
    app: cat


